from pydantic_settings import BaseSettings
from pydantic import Field
from functools import lru_cache

class Settings(BaseSettings):
    project_name: str = "EnerVision - AI Energy Forecasting API"
    version: str = "0.1.0"
    debug: bool = False
    
    ibm_watsonx_api_key: str = Field(..., env="IBM_WATSONX_API_KEY")
    ibm_watsonx_url: str = Field(..., env="IBM_WATSONX_URL")
    ibm_watsonx_project_id: str = Field(..., env="IBM_WATSONX_PROJECT_ID")
    
    default_prediction_length: int = 96
    default_context_length: int = 720
    model_ensemble_weights: list = [0.5, 0.3, 0.2]
    
    class Config:
        env_file = ".env"

@lru_cache()
def get_settings():
    return Settings()